name: Cypress cucumber bdd
on: push
jobs:
  run-cypress-bdd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm test
      - name: Cypress Test Report
        uses: actions/upload-artifact@v4
        with:
          name: Cucumber HTML Report
          path: cypress/reports/html
